# 错误

## 捕获错误

> 自定义 类
```java
class  User {
 public void test(int x,int y) throws ArithmeticException {
    System.out.println(x / y);
 }
```

使用 `u.test` 加上 `.try` 自动添加错误信息
> 测试类
```java
User u = new User();
try {
  u.test(1,0);
} catch (ArithmeticException e) {
  e.printStackTrace();
}
```

